import { ACTIVE_STRATEGY_MODE, AVAILABLE_ASSETS } from './constants'

export const defaultForm = {
  assets: [...AVAILABLE_ASSETS],
  strategy_mode: ACTIVE_STRATEGY_MODE,
  start_date: '2016-01-01',
  end_date: '',
  timeframe: '1Day',
  market_data_provider: 'alpaca',
  alpaca_feed: 'iex',
  alpaca_adjustment: 'all',
  rotation_models: ['xgboost_utility'],
  rotation_horizon_days: 40,
  rotation_minimum_training_rows: 700,
  rotation_walk_forward_enabled: true,
  rotation_walk_forward_calibration_days: 126,
  rotation_walk_forward_test_days: 504,
  rotation_walk_forward_min_test_days: 126,
  rotation_purge_days: 60,
  rotation_downside_penalty: 0.20,
  rotation_drawdown_penalty: 0.35,
  rotation_min_holding_days: 2,
  rotation_min_expected_edge: 0.001,
  rotation_cash_threshold: 0.0,
  rotation_switch_margin: 0.005,
  rotation_switch_margin_candidates: [0.0, 0.0025, 0.005, 0.01],
  rotation_xgb_n_estimators: 300,
  rotation_xgb_learning_rate: 0.035,
  rotation_xgb_max_depth: 3,
  rotation_accelerator: 'auto',
  rotation_allow_cpu_fallback: true,
  rotation_parallel_models: true,
  rotation_xgb_repetitions: 1,
  rotation_qrdqn_repetitions: 1,
  rotation_seed_step: 1000,
  qrdqn_training_steps: 15000,
  qrdqn_parallel_folds: 2,
  qrdqn_early_stopping_enabled: false,
  qrdqn_early_stopping_patience: 4,
  qrdqn_min_training_steps: 5000,
  qrdqn_episode_days: 252,
  qrdqn_replay_size: 30000,
  qrdqn_learning_starts: 750,
  qrdqn_batch_size: 128,
  qrdqn_learning_rate: 0.0003,
  qrdqn_gamma: 0.99,
  qrdqn_n_step: 10,
  qrdqn_n_quantiles: 25,
  qrdqn_hidden_dim: 128,
  qrdqn_target_update_steps: 250,
  qrdqn_eval_every_steps: 1000,
  qrdqn_epsilon_start: 1.0,
  qrdqn_epsilon_end: 0.05,
  initial_capital: 10000,
  whole_shares: false,
  slippage_bps: 0,
  commission_rate: 0,
  sec_fee_rate: 0.0000206,
  taf_fee_per_share: 0.000195,
  taf_fee_cap: 9.79,
  cat_fee_per_share: 0.000003,
  xgb_min_child_weight: 5,
  xgb_subsample: 0.85,
  xgb_colsample_bytree: 0.85,
  xgb_reg_alpha: 0.1,
  xgb_reg_lambda: 2,
  xgb_n_jobs: -1,
  yfinance_auto_adjust: true,
  yfinance_repair: false,
  yfinance_timeout: 30,
  yfinance_fallback_period: 'max',
  mongo_cache_enabled: true,
  mongo_refresh_overlap_days: 7,
  mongo_write_batch_size: 1000,
  random_state: 42,
}

export const numericFields = [
  'rotation_horizon_days',
  'rotation_minimum_training_rows',
  'rotation_walk_forward_calibration_days',
  'rotation_walk_forward_test_days',
  'rotation_walk_forward_min_test_days',
  'rotation_purge_days',
  'rotation_downside_penalty',
  'rotation_drawdown_penalty',
  'rotation_min_holding_days',
  'rotation_min_expected_edge',
  'rotation_cash_threshold',
  'rotation_switch_margin',
  'rotation_xgb_n_estimators',
  'rotation_xgb_learning_rate',
  'rotation_xgb_max_depth',
  'rotation_xgb_repetitions',
  'rotation_qrdqn_repetitions',
  'rotation_seed_step',
  'qrdqn_training_steps',
  'qrdqn_parallel_folds',
  'qrdqn_early_stopping_patience',
  'qrdqn_min_training_steps',
  'qrdqn_episode_days',
  'qrdqn_replay_size',
  'qrdqn_learning_starts',
  'qrdqn_batch_size',
  'qrdqn_learning_rate',
  'qrdqn_gamma',
  'qrdqn_n_step',
  'qrdqn_n_quantiles',
  'qrdqn_hidden_dim',
  'qrdqn_target_update_steps',
  'qrdqn_eval_every_steps',
  'qrdqn_epsilon_start',
  'qrdqn_epsilon_end',
  'initial_capital',
  'slippage_bps',
  'commission_rate',
  'sec_fee_rate',
  'taf_fee_per_share',
  'taf_fee_cap',
  'cat_fee_per_share',
  'xgb_min_child_weight',
  'xgb_subsample',
  'xgb_colsample_bytree',
  'xgb_reg_alpha',
  'xgb_reg_lambda',
  'xgb_n_jobs',
  'yfinance_timeout',
  'mongo_refresh_overlap_days',
  'mongo_write_batch_size',
  'random_state',
]

