import { ACTIVE_STRATEGY_MODE } from './constants'

export const defaultForm = {
  assets: ['NVDA', 'AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'TSLA', 'AMD', 'JPM', 'SPY'],
  model_backends: ['histgb'],
  start_date: '2016-01-01',
  end_date: '',
  timeframe: '1Day',
  strategy_mode: ACTIVE_STRATEGY_MODE,

  future_horizon: 5,
  extrema_lookback: 10,
  reversal_threshold: 0.03,
  extrema_tolerance: 0.01,
  event_tolerance_bars: 2,

  calibration_fraction: 0.15,
  test_fraction: 0.2,
  retrain_every_bars: 63,
  minimum_training_rows: 500,
  threshold_min: 0.25,
  threshold_max: 0.85,
  threshold_step: 0.025,
  bottom_threshold_max: 0.75,
  top_threshold_max: 0.85,
  bottom_min_precision: 0.6,
  bottom_min_recall: 0.3,
  top_min_precision: 0.45,
  top_min_recall: 0,
  minimum_calibration_signals: 3,
  bottom_min_calibration_signals: 3,
  top_min_calibration_signals: 3,

  entry_max_rsi: 60,
  entry_require_above_ema50: false,
  entry_cooldown_bars: 3,

  trend_pullback_entry_enabled: true,
  trend_pullback_ema: 20,
  trend_pullback_rsi_min: 40,
  trend_pullback_rsi_max: 65,
  trend_pullback_touch_tolerance: 0.02,
  trend_pullback_require_positive_return: true,

  adaptive_bull_regime_enabled: true,
  bull_regime_ema_fast: 20,
  bull_regime_ema_slow: 50,
  bull_regime_require_price_above_slow: true,
  bull_regime_require_slow_ema_rising: true,
  bull_regime_entry_enabled: false,
  bull_regime_entry_confirmation_bars: 3,

  exit_top_probability: false,
  exit_trend_breakdown: true,
  exit_atr_trailing_stop: true,
  minimum_holding_bars: 3,
  atr_trailing_multiplier: 3,
  top_tighten_trailing: true,
  tightened_atr_multiplier: 1.5,
  trend_exit_ema_fast: 5,
  trend_exit_ema_slow: 20,
  trend_breakdown_confirmation_bars: 2,
  trend_breakdown_require_slow_ema_decline: true,

  bull_exit_ema_fast: 20,
  bull_exit_ema_slow: 50,
  bull_exit_confirmation_bars: 3,
  bull_exit_require_slow_ema_decline: true,

  exit_fibonacci_target: true,
  fibonacci_target_ratio: 1.618,
  fibonacci_swing_lookback: 50,
  fibonacci_low_lookback: 5,

  mtf_top_signal_timeframe: '1Week',
  mtf_top_confirmation_timeframe: '1Day',
  mtf_top_future_horizon: 4,
  mtf_top_extrema_lookback: 10,
  mtf_top_reversal_threshold: 0.10,
  mtf_top_extrema_tolerance: 0.03,
  mtf_top_probability_floor: 0.60,
  mtf_top_retrain_every_bars: 13,
  mtf_top_minimum_training_rows: 500,
  mtf_daily_confirmation_ema: 20,
  mtf_daily_confirmation_bars: 2,
  mtf_daily_require_negative_return: true,
  mtf_daily_require_ema_decline: true,
  mtf_daily_require_lower_high: false,
  mtf_top_signal_valid_days: 20,
  mtf_top_min_position_return: 0.0,
  mtf_top_high_lookback_weeks: 26,
  mtf_top_max_distance_from_high: 0.10,
  mtf_exit_quality_horizon_days: 20,

  exit_risk_model_backend: 'xgboost',
  exit_risk_compare_models: true,
  exit_risk_model_backends: ['xgboost', 'histgb', 'catboost'],
  exit_risk_signal_timeframe: '1Week',
  exit_risk_horizon_weeks: 8,
  exit_risk_event_tolerance_weeks: 2,
  exit_risk_down_barrier: 0.12,
  exit_risk_up_barrier: 0.08,
  exit_risk_probability_floor: 0.60,
  exit_risk_threshold_max: 0.85,
  exit_risk_min_precision: 0.55,
  exit_risk_min_recall: 0.20,
  exit_risk_min_calibration_signals: 5,
  exit_risk_hard_calibration_gate: true,
  exit_risk_retrain_every_bars: 26,
  exit_risk_minimum_training_rows: 300,
  exit_risk_reentry_enabled: true,
  exit_risk_reentry_cooldown_days: 5,

  swing_exit_horizon_days: 10,
  swing_exit_event_tolerance_days: 3,
  swing_exit_down_barrier: 0.06,
  swing_exit_up_barrier: 0.04,
  swing_exit_retrain_every_bars: 20,
  swing_exit_minimum_training_rows: 500,

  rotation_models: ['xgboost_utility'],
  rotation_horizon_days: 40,
  rotation_minimum_training_rows: 700,
  rotation_walk_forward_enabled: true,
  rotation_walk_forward_calibration_days: 126,
  rotation_walk_forward_test_days: 504,
  rotation_walk_forward_min_test_days: 126,
  rotation_purge_days: 60,
  rotation_downside_penalty: 0.20,
  rotation_drawdown_penalty: 0.35,
  rotation_min_holding_days: 2,
  rotation_min_expected_edge: 0.001,
  rotation_cash_threshold: 0.0,
  rotation_switch_margin: 0.005,
  rotation_switch_margin_candidates: [0.0, 0.0025, 0.005, 0.01],
  rotation_xgb_n_estimators: 300,
  rotation_xgb_learning_rate: 0.035,
  rotation_xgb_max_depth: 3,
  rotation_accelerator: 'auto',
  rotation_allow_cpu_fallback: true,
  rotation_parallel_models: true,
  rotation_xgb_repetitions: 1,
  rotation_qrdqn_repetitions: 1,
  rotation_seed_step: 1000,

  qrdqn_training_steps: 15000,
  qrdqn_parallel_folds: 2,
  qrdqn_early_stopping_enabled: false,
  qrdqn_early_stopping_patience: 4,
  qrdqn_min_training_steps: 5000,
  qrdqn_episode_days: 252,
  qrdqn_replay_size: 30000,
  qrdqn_learning_starts: 750,
  qrdqn_batch_size: 128,
  qrdqn_learning_rate: 0.0003,
  qrdqn_gamma: 0.99,
  qrdqn_n_quantiles: 25,
  qrdqn_hidden_dim: 128,
  qrdqn_target_update_steps: 250,
  qrdqn_eval_every_steps: 1000,
  qrdqn_epsilon_start: 1.0,
  qrdqn_epsilon_end: 0.05,
  qrdqn_device: 'cpu',

  initial_capital: 10000,
  whole_shares: false,
  slippage_bps: 0,
  commission_rate: 0,
  sec_fee_rate: 0.0000206,
  taf_fee_per_share: 0.000195,
  taf_fee_cap: 9.79,
  cat_fee_per_share: 0.000003,

  hist_max_iter: 300,
  hist_learning_rate: 0.04,
  hist_max_leaf_nodes: 15,
  hist_min_samples_leaf: 25,
  hist_l2_regularization: 2,

  xgb_n_estimators: 350,
  xgb_learning_rate: 0.035,
  xgb_max_depth: 3,
  xgb_min_child_weight: 5,
  xgb_subsample: 0.85,
  xgb_colsample_bytree: 0.85,
  xgb_gamma: 0,
  xgb_reg_alpha: 0.1,
  xgb_reg_lambda: 2,
  xgb_n_jobs: -1,
  xgb_device: 'cpu',

  catboost_iterations: 350,
  catboost_learning_rate: 0.035,
  catboost_depth: 6,
  catboost_l2_leaf_reg: 3.0,
  catboost_random_strength: 1.0,
  catboost_thread_count: -1,

  max_parallel_workers: 3,
  cuda_parallel_workers: 1,

  market_data_provider: 'alpaca',
  alpaca_feed: 'iex',
  alpaca_adjustment: 'all',
  yfinance_auto_adjust: true,
  yfinance_repair: false,
  yfinance_timeout: 30,
  yfinance_fallback_period: 'max',
  mongo_cache_enabled: true,
  mongo_refresh_overlap_days: 7,
  mongo_write_batch_size: 1000,
  random_state: 42,
}

export const numericFields = [
  'future_horizon',
  'extrema_lookback',
  'reversal_threshold',
  'extrema_tolerance',
  'event_tolerance_bars',
  'calibration_fraction',
  'test_fraction',
  'retrain_every_bars',
  'minimum_training_rows',
  'threshold_min',
  'threshold_max',
  'threshold_step',
  'bottom_threshold_max',
  'top_threshold_max',
  'bottom_min_precision',
  'bottom_min_recall',
  'top_min_precision',
  'top_min_recall',
  'minimum_calibration_signals',
  'bottom_min_calibration_signals',
  'top_min_calibration_signals',
  'entry_max_rsi',
  'entry_cooldown_bars',
  'trend_pullback_ema',
  'trend_pullback_rsi_min',
  'trend_pullback_rsi_max',
  'trend_pullback_touch_tolerance',
  'bull_regime_ema_fast',
  'bull_regime_ema_slow',
  'bull_regime_entry_confirmation_bars',
  'minimum_holding_bars',
  'atr_trailing_multiplier',
  'tightened_atr_multiplier',
  'trend_exit_ema_fast',
  'trend_exit_ema_slow',
  'trend_breakdown_confirmation_bars',
  'bull_exit_ema_fast',
  'bull_exit_ema_slow',
  'bull_exit_confirmation_bars',
  'fibonacci_target_ratio',
  'fibonacci_swing_lookback',
  'fibonacci_low_lookback',
  'mtf_top_future_horizon',
  'mtf_top_extrema_lookback',
  'mtf_top_reversal_threshold',
  'mtf_top_extrema_tolerance',
  'mtf_top_probability_floor',
  'mtf_top_retrain_every_bars',
  'mtf_top_minimum_training_rows',
  'mtf_daily_confirmation_ema',
  'mtf_daily_confirmation_bars',
  'mtf_top_signal_valid_days',
  'mtf_top_min_position_return',
  'mtf_top_high_lookback_weeks',
  'mtf_top_max_distance_from_high',
  'mtf_exit_quality_horizon_days',
  'exit_risk_horizon_weeks',
  'exit_risk_event_tolerance_weeks',
  'exit_risk_down_barrier',
  'exit_risk_up_barrier',
  'exit_risk_probability_floor',
  'exit_risk_threshold_max',
  'exit_risk_min_precision',
  'exit_risk_min_recall',
  'exit_risk_min_calibration_signals',
  'exit_risk_retrain_every_bars',
  'exit_risk_minimum_training_rows',
  'exit_risk_reentry_cooldown_days',
  'swing_exit_horizon_days',
  'swing_exit_event_tolerance_days',
  'swing_exit_down_barrier',
  'swing_exit_up_barrier',
  'swing_exit_retrain_every_bars',
  'swing_exit_minimum_training_rows',
  'rotation_horizon_days',
  'rotation_minimum_training_rows',
  'rotation_walk_forward_calibration_days',
  'rotation_walk_forward_test_days',
  'rotation_walk_forward_min_test_days',
  'rotation_purge_days',
  'rotation_downside_penalty',
  'rotation_drawdown_penalty',
  'rotation_min_holding_days',
  'rotation_min_expected_edge',
  'rotation_cash_threshold',
  'rotation_switch_margin',
  'rotation_xgb_n_estimators',
  'rotation_xgb_learning_rate',
  'rotation_xgb_max_depth',
  'rotation_xgb_repetitions',
  'rotation_qrdqn_repetitions',
  'rotation_seed_step',
  'qrdqn_training_steps',
  'qrdqn_parallel_folds',
  'qrdqn_early_stopping_patience',
  'qrdqn_min_training_steps',
  'qrdqn_episode_days',
  'qrdqn_replay_size',
  'qrdqn_learning_starts',
  'qrdqn_batch_size',
  'qrdqn_learning_rate',
  'qrdqn_gamma',
  'qrdqn_n_quantiles',
  'qrdqn_hidden_dim',
  'qrdqn_target_update_steps',
  'qrdqn_eval_every_steps',
  'qrdqn_epsilon_start',
  'qrdqn_epsilon_end',
  'initial_capital',
  'slippage_bps',
  'commission_rate',
  'sec_fee_rate',
  'taf_fee_per_share',
  'taf_fee_cap',
  'cat_fee_per_share',
  'hist_max_iter',
  'hist_learning_rate',
  'hist_max_leaf_nodes',
  'hist_min_samples_leaf',
  'hist_l2_regularization',
  'xgb_n_estimators',
  'xgb_learning_rate',
  'xgb_max_depth',
  'xgb_min_child_weight',
  'xgb_subsample',
  'xgb_colsample_bytree',
  'xgb_gamma',
  'xgb_reg_alpha',
  'xgb_reg_lambda',
  'xgb_n_jobs',
  'catboost_iterations',
  'catboost_learning_rate',
  'catboost_depth',
  'catboost_l2_leaf_reg',
  'catboost_random_strength',
  'catboost_thread_count',
  'max_parallel_workers',
  'cuda_parallel_workers',
  'yfinance_timeout',
  'mongo_refresh_overlap_days',
  'mongo_write_batch_size',
  'random_state',
]
