import {
  AVAILABLE_ASSETS,
  dayTradeAlpacaStartDate,
  swingAlpacaStartDate,
} from './constants'

export const STRATEGY_PRESETS = {
  COMPOUND_ROTATION_SWING_1W: {
    strategy_mode: 'COMPOUND_ROTATION_SWING_1W',
    timeframe: '1Day',
    start_date: swingAlpacaStartDate(),
    market_data_provider: 'alpaca',

    rotation_models: ['xgboost_utility'],
    rotation_horizon_days: 40,
    rotation_minimum_training_rows: 700,
    rotation_walk_forward_enabled: true,
    rotation_walk_forward_calibration_days: 126,
    rotation_walk_forward_test_days: 504,
    rotation_walk_forward_min_test_days: 126,
    rotation_purge_days: 60,
    rotation_downside_penalty: 0.20,
    rotation_drawdown_penalty: 0.35,
    rotation_min_holding_days: 2,
    rotation_min_expected_edge: 0.001,
    rotation_cash_threshold: 0.0,
    rotation_switch_margin: 0.005,
    rotation_switch_margin_candidates: [0.0, 0.0025, 0.005, 0.01],

    rotation_xgb_n_estimators: 300,
    rotation_xgb_learning_rate: 0.035,
    rotation_xgb_max_depth: 3,
    rotation_accelerator: 'auto',
    rotation_allow_cpu_fallback: true,
    rotation_parallel_models: true,
    rotation_xgb_repetitions: 1,
    rotation_qrdqn_repetitions: 1,
    rotation_seed_step: 1000,

    qrdqn_training_steps: 15000,
    qrdqn_parallel_folds: 2,
    qrdqn_early_stopping_enabled: false,
    qrdqn_early_stopping_patience: 4,
    qrdqn_min_training_steps: 5000,
    qrdqn_episode_days: 252,
    qrdqn_replay_size: 30000,
    qrdqn_learning_starts: 750,
    qrdqn_batch_size: 128,
    qrdqn_learning_rate: 0.0003,
    qrdqn_gamma: 0.99,
    qrdqn_n_quantiles: 25,
    qrdqn_hidden_dim: 128,
    qrdqn_target_update_steps: 250,
    qrdqn_eval_every_steps: 1000,
    qrdqn_epsilon_start: 1.0,
    qrdqn_epsilon_end: 0.05,
    qrdqn_device: 'cpu',

    model_backends: ['histgb'],
  },
  COMPOUND_ROTATION_DAY_TRADE_OPEN_CLOSE: {
    strategy_mode: 'COMPOUND_ROTATION_DAY_TRADE_OPEN_CLOSE',
    timeframe: '15Min',
    start_date: dayTradeAlpacaStartDate(),
    market_data_provider: 'alpaca',

    // One decision per market session. The 15-minute bars are source data only;
    // the engine aggregates them into a leak-free Open→Close session dataset. The current opening print is never used to choose an order that is also filled at that same open.
    rotation_models: ['xgboost_utility', 'qrdqn'],
    rotation_horizon_days: 1,
    rotation_minimum_training_rows: 500,
    rotation_walk_forward_enabled: true,
    rotation_walk_forward_calibration_days: 126,
    rotation_walk_forward_test_days: 126,
    rotation_walk_forward_min_test_days: 63,
    rotation_purge_days: 1,
    rotation_downside_penalty: 0.20,
    rotation_drawdown_penalty: 0.35,
    rotation_min_holding_days: 0,
    rotation_min_expected_edge: 0.0,
    rotation_cash_threshold: 0.0,
    rotation_switch_margin: 0.0,
    rotation_switch_margin_candidates: [0.0],

    rotation_xgb_n_estimators: 300,
    rotation_xgb_learning_rate: 0.035,
    rotation_xgb_max_depth: 3,
    rotation_parallel_models: true,
    rotation_xgb_repetitions: 1,
    rotation_qrdqn_repetitions: 1,
    qrdqn_training_steps: 10000,
    qrdqn_parallel_folds: 2,
    qrdqn_early_stopping_enabled: false,
    qrdqn_min_training_steps: 5000,
    qrdqn_episode_days: 252,
    qrdqn_replay_size: 30000,
    qrdqn_learning_starts: 750,
    qrdqn_batch_size: 128,
    qrdqn_learning_rate: 0.0003,
    qrdqn_gamma: 0.0,
    qrdqn_n_quantiles: 25,
    qrdqn_hidden_dim: 128,
    qrdqn_target_update_steps: 250,
    qrdqn_eval_every_steps: 1000,
    qrdqn_epsilon_start: 1.0,
    qrdqn_epsilon_end: 0.05,
    qrdqn_device: 'cpu',

    model_backends: ['histgb'],
  },
}

export const SWING_HEAD_TO_HEAD_CONFIG = {
  ...STRATEGY_PRESETS.COMPOUND_ROTATION_SWING_1W,
  assets: [...AVAILABLE_ASSETS],
  initial_capital: 10000,
  rotation_models: ['xgboost_utility', 'qrdqn'],
  rotation_xgb_repetitions: 1,
  rotation_qrdqn_repetitions: 1,
  random_state: 42,
  qrdqn_training_steps: 10000,
  qrdqn_early_stopping_enabled: true,
  qrdqn_min_training_steps: 5000,
  qrdqn_early_stopping_patience: 100,
  slippage_bps: 0,
  commission_rate: 0,
}

export const ASSET_DEFAULT_SETUPS = {
  NVDA: {
    setup_name: 'NVDA · 4Weeks · Bottom Reversal Fibonacci',
    start_date: '2000-01-01',
    timeframe: '4Weeks',
    future_horizon: 3,
    extrema_lookback: 6,
    reversal_threshold: 0.02,
    extrema_tolerance: 0.05,
    event_tolerance_bars: 1,
    retrain_every_bars: 4,
    minimum_training_rows: 100,
    minimum_calibration_signals: 1,
    entry_cooldown_bars: 0,
    trend_pullback_entry_enabled: false,
    trend_pullback_ema: 20,
    trend_pullback_rsi_min: 40,
    trend_pullback_rsi_max: 65,
    trend_pullback_touch_tolerance: 0.01,
    trend_pullback_require_positive_return: true,
    adaptive_bull_regime_enabled: true,
    bull_regime_ema_fast: 20,
    bull_regime_ema_slow: 50,
    bull_regime_require_price_above_slow: true,
    bull_regime_require_slow_ema_rising: true,
    bull_regime_entry_enabled: true,
    bull_regime_entry_confirmation_bars: 3,
    exit_top_probability: false,
    exit_trend_breakdown: true,
    exit_atr_trailing_stop: false,
    minimum_holding_bars: 1,
    atr_trailing_multiplier: 4,
    top_tighten_trailing: false,
    tightened_atr_multiplier: 2.5,
    trend_exit_ema_fast: 20,
    trend_exit_ema_slow: 50,
    trend_breakdown_confirmation_bars: 2,
    trend_breakdown_require_slow_ema_decline: true,
    bull_exit_ema_fast: 20,
    bull_exit_ema_slow: 50,
    bull_exit_confirmation_bars: 2,
    bull_exit_require_slow_ema_decline: true,
    exit_fibonacci_target: false,
    fibonacci_target_ratio: 1.618,
    fibonacci_swing_lookback: 7,
    fibonacci_low_lookback: 2,
  },
}
