import { AVAILABLE_ASSETS, dayTradeAlpacaStartDate, swingAlpacaStartDate } from './constants'

const swingBase = {
  timeframe: '1Day',
  start_date: swingAlpacaStartDate(),
  market_data_provider: 'alpaca',
  rotation_horizon_days: 40,
  rotation_minimum_training_rows: 700,
  rotation_walk_forward_enabled: true,
  rotation_walk_forward_calibration_days: 126,
  rotation_walk_forward_test_days: 504,
  rotation_walk_forward_min_test_days: 126,
  rotation_purge_days: 60,
  rotation_downside_penalty: 0.20,
  rotation_drawdown_penalty: 0.35,
  rotation_min_holding_days: 2,
  rotation_min_expected_edge: 0.001,
  rotation_cash_threshold: 0.0,
  rotation_switch_margin: 0.005,
  rotation_switch_margin_candidates: [0.0, 0.0025, 0.005, 0.01],
  rotation_xgb_n_estimators: 300,
  rotation_xgb_learning_rate: 0.035,
  rotation_xgb_max_depth: 3,
  rotation_xgb_repetitions: 1,
  rotation_qrdqn_repetitions: 1,
  qrdqn_training_steps: 15000,
  qrdqn_min_training_steps: 5000,
  qrdqn_gamma: 0.99,
}

export const STRATEGY_PRESETS = {
  COMPOUND_ROTATION_SWING_XGBOOST: {
    ...swingBase,
    strategy_mode: 'COMPOUND_ROTATION_SWING_XGBOOST',
    rotation_models: ['xgboost_utility'],
  },
  COMPOUND_ROTATION_SWING_QRDQN: {
    ...swingBase,
    strategy_mode: 'COMPOUND_ROTATION_SWING_QRDQN',
    rotation_models: ['qrdqn'],
    qrdqn_n_step: 10,
  },
  COMPOUND_ROTATION_DAY_TRADE_OPEN_CLOSE: {
    strategy_mode: 'COMPOUND_ROTATION_DAY_TRADE_OPEN_CLOSE',
    timeframe: '15Min',
    start_date: dayTradeAlpacaStartDate(),
    market_data_provider: 'alpaca',
    rotation_models: ['xgboost_utility', 'qrdqn'],
    rotation_horizon_days: 1,
    rotation_minimum_training_rows: 500,
    rotation_walk_forward_enabled: true,
    rotation_walk_forward_calibration_days: 126,
    rotation_walk_forward_test_days: 126,
    rotation_walk_forward_min_test_days: 63,
    rotation_purge_days: 1,
    rotation_downside_penalty: 0.20,
    rotation_drawdown_penalty: 0.35,
    rotation_min_holding_days: 0,
    rotation_min_expected_edge: 0,
    rotation_cash_threshold: 0,
    rotation_switch_margin: 0,
    rotation_switch_margin_candidates: [0],
    rotation_xgb_n_estimators: 300,
    rotation_xgb_learning_rate: 0.035,
    rotation_xgb_max_depth: 3,
    rotation_xgb_repetitions: 1,
    rotation_qrdqn_repetitions: 1,
    qrdqn_training_steps: 10000,
    qrdqn_min_training_steps: 5000,
    qrdqn_gamma: 0,
    qrdqn_n_step: 1,
  },
}

export const SWING_QRDQN_QR0_CONFIG = {
  ...STRATEGY_PRESETS.COMPOUND_ROTATION_SWING_QRDQN,
  assets: [...AVAILABLE_ASSETS],
  initial_capital: 10000,
  random_state: 42,
  slippage_bps: 0,
  commission_rate: 0,
  qrdqn_n_step: 1,
}

export const SWING_QRDQN_QR1_CONFIG = {
  ...STRATEGY_PRESETS.COMPOUND_ROTATION_SWING_QRDQN,
  assets: [...AVAILABLE_ASSETS],
  initial_capital: 10000,
  random_state: 42,
  slippage_bps: 0,
  commission_rate: 0,
  qrdqn_n_step: 5,
}

export const SWING_QRDQN_QR2_CONFIG = {
  ...STRATEGY_PRESETS.COMPOUND_ROTATION_SWING_QRDQN,
  assets: [...AVAILABLE_ASSETS],
  initial_capital: 10000,
  random_state: 42,
  slippage_bps: 0,
  commission_rate: 0,
  qrdqn_n_step: 10,
}
